#create a new workflow file to deploy a app on github action on local minikube 
name: deploy_test

on: push
jobs: 
    deploy:
        name: deploy to minikube
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: build and push to docker
              uses: docker/build-push-action@v2
              with:
                repository: ${{ github.repository }}
                tag_with_ref: true
                tags_with_sha: true
                tag: ${{ github.sha }}

