#create a new workflow file to deploy a app on github action on local minikube 
name: deploy_test

on: push
jobs: 
    deploy:
        name: deploy to minikube
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: build and push to docker
              uses: docker/build-push-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: ${{ github.repository }}
                tag_with_ref: true
                tags_with_sha: true
                tag: ${{ github.sha }}
            - name: deploy to minikube
              uses: appleboy/kubectl-action@master
              env:
                KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
              with:
                args: set image --record deployment/test test-gha=${{ github.repository }}:${{ github.sha }}
            - name: show deployment status
              uses: appleboy/kubectl-action@master
              env:
                KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
              with:
                args: rollout status deployment/test